// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {voice} from '../models';

export function ListModels(arg1:string):Promise<Array<string>>;

export function ListVoices(arg1:string):Promise<Array<string>>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function Ping(arg1:string):Promise<voice.PingResult>;

export function StartVoiceSession(arg1:string):Promise<void>;

export function Synthesize(arg1:string,arg2:string,arg3:number,arg4:string):Promise<voice.SpeechResult>;

export function Transcribe(arg1:string,arg2:string,arg3:string):Promise<string>;

export function VoiceListenExtend(arg1:string):Promise<void>;

export function VoiceResult(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VoiceResultClosed(arg1:string):Promise<void>;
