// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListModels(arg1) {
  return window['go']['voice']['voiceController']['ListModels'](arg1);
}

export function ListVoices() {
  return window['go']['voice']['voiceController']['ListVoices']();
}

export function OnShutdown(arg1) {
  return window['go']['voice']['voiceController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['voice']['voiceController']['OnStartup'](arg1);
}

export function Ping(arg1) {
  return window['go']['voice']['voiceController']['Ping'](arg1);
}

export function StartVoiceSession(arg1) {
  return window['go']['voice']['voiceController']['StartVoiceSession'](arg1);
}

export function Synthesize(arg1, arg2, arg3) {
  return window['go']['voice']['voiceController']['Synthesize'](arg1, arg2, arg3);
}

export function Transcribe(arg1, arg2) {
  return window['go']['voice']['voiceController']['Transcribe'](arg1, arg2);
}

export function VoiceListenExtend(arg1) {
  return window['go']['voice']['voiceController']['VoiceListenExtend'](arg1);
}

export function VoiceResult(arg1, arg2, arg3) {
  return window['go']['voice']['voiceController']['VoiceResult'](arg1, arg2, arg3);
}

export function VoiceResultClosed(arg1) {
  return window['go']['voice']['voiceController']['VoiceResultClosed'](arg1);
}
