// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAgent(arg1) {
  return window['go']['controller']['agentController']['CreateAgent'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['controller']['agentController']['DeleteAgent'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['controller']['agentController']['GetAgent'](arg1);
}

export function ListAgents() {
  return window['go']['controller']['agentController']['ListAgents']();
}

export function ListAvailableMcpServers(arg1) {
  return window['go']['controller']['agentController']['ListAvailableMcpServers'](arg1);
}

export function ListAvailableSkills(arg1) {
  return window['go']['controller']['agentController']['ListAvailableSkills'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['agentController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['agentController']['OnStartup'](arg1);
}

export function UpdateAgent(arg1) {
  return window['go']['controller']['agentController']['UpdateAgent'](arg1);
}
