// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function CreateAgent(arg1:dto.CreateAgentRequest):Promise<dto.AgentResponse>;

export function DeleteAgent(arg1:string):Promise<void>;

export function GetAgent(arg1:string):Promise<dto.AgentResponse>;

export function ListAgents():Promise<Array<dto.AgentResponse>>;

export function ListAvailableMcpServers(arg1:string):Promise<Array<string>>;

export function ListAvailableSkills(arg1:string):Promise<Array<dto.SkillInfo>>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function UpdateAgent(arg1:dto.UpdateAgentRequest):Promise<dto.AgentResponse>;
