// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function GetChangelog():Promise<entity.Changelog>;

export function GetVersion():Promise<string>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;
