// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChangelog() {
  return window['go']['controller']['changelogController']['GetChangelog']();
}

export function GetVersion() {
  return window['go']['controller']['changelogController']['GetVersion']();
}

export function OnShutdown(arg1) {
  return window['go']['controller']['changelogController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['changelogController']['OnStartup'](arg1);
}
