// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function BrowseDirectory():Promise<string>;

export function ClearSessionLogs():Promise<void>;

export function GetConfig():Promise<dto.ConfigResponse>;

export function GetDatabasePath():Promise<string>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function ResetDatabase():Promise<void>;

export function SaveConfig(arg1:dto.SaveConfigRequest):Promise<void>;
