// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory() {
  return window['go']['controller']['configController']['BrowseDirectory']();
}

export function ClearSessionLogs() {
  return window['go']['controller']['configController']['ClearSessionLogs']();
}

export function GetConfig() {
  return window['go']['controller']['configController']['GetConfig']();
}

export function GetDatabasePath() {
  return window['go']['controller']['configController']['GetDatabasePath']();
}

export function OnShutdown(arg1) {
  return window['go']['controller']['configController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['configController']['OnStartup'](arg1);
}

export function ResetDatabase() {
  return window['go']['controller']['configController']['ResetDatabase']();
}

export function SaveConfig(arg1) {
  return window['go']['controller']['configController']['SaveConfig'](arg1);
}
