// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDir(arg1, arg2) {
  return window['go']['controller']['fileController']['CreateDir'](arg1, arg2);
}

export function CreateFile(arg1, arg2) {
  return window['go']['controller']['fileController']['CreateFile'](arg1, arg2);
}

export function DeletePath(arg1, arg2, arg3) {
  return window['go']['controller']['fileController']['DeletePath'](arg1, arg2, arg3);
}

export function ListDir(arg1, arg2) {
  return window['go']['controller']['fileController']['ListDir'](arg1, arg2);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['fileController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['fileController']['OnStartup'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['controller']['fileController']['ReadFile'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['controller']['fileController']['RenamePath'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['controller']['fileController']['WriteFile'](arg1, arg2, arg3);
}
