// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function CreateDir(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeletePath(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ListDir(arg1:string,arg2:string):Promise<Array<dto.FileEntryResponse>>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function ReadFile(arg1:string,arg2:string):Promise<dto.FileContentResponse>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
