// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMindmapBoard(arg1, arg2) {
  return window['go']['controller']['mindmapController']['ClearMindmapBoard'](arg1, arg2);
}

export function GetMindmap(arg1, arg2) {
  return window['go']['controller']['mindmapController']['GetMindmap'](arg1, arg2);
}

export function ListBoards(arg1) {
  return window['go']['controller']['mindmapController']['ListBoards'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['mindmapController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['mindmapController']['OnStartup'](arg1);
}

export function RemoveMindmapNode(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['mindmapController']['RemoveMindmapNode'](arg1, arg2, arg3, arg4);
}

export function SetMindmapNode(arg1, arg2, arg3) {
  return window['go']['controller']['mindmapController']['SetMindmapNode'](arg1, arg2, arg3);
}
