// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function ClearMindmapBoard(arg1:string,arg2:string):Promise<void>;

export function GetMindmap(arg1:string,arg2:string):Promise<Array<dto.MindmapNodeResponse>>;

export function ListBoards(arg1:string):Promise<Array<string>>;

export function MoveBoard(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RemoveMindmapNode(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetMindmapNode(arg1:string,arg2:string,arg3:dto.MindmapNodeRequest):Promise<dto.MindmapNodeResponse>;
