// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {context} from '../models';

export function DisableRemoteAccess():Promise<remote.Status>;

export function EnableRemoteAccess():Promise<remote.Status>;

export function GetRemoteAccessStatus():Promise<remote.Status>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RegenerateRemotePasscode():Promise<remote.Status>;
