// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableRemoteAccess() {
  return window['go']['controller']['remoteController']['DisableRemoteAccess']();
}

export function EnableRemoteAccess() {
  return window['go']['controller']['remoteController']['EnableRemoteAccess']();
}

export function GetRemoteAccessStatus() {
  return window['go']['controller']['remoteController']['GetRemoteAccessStatus']();
}

export function OnShutdown(arg1) {
  return window['go']['controller']['remoteController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['remoteController']['OnStartup'](arg1);
}

export function RegenerateRemotePasscode() {
  return window['go']['controller']['remoteController']['RegenerateRemotePasscode']();
}
