// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory() {
  return window['go']['controller']['repoController']['BrowseDirectory']();
}

export function GetRepo(arg1) {
  return window['go']['controller']['repoController']['GetRepo'](arg1);
}

export function ListReposByWorkspace(arg1) {
  return window['go']['controller']['repoController']['ListReposByWorkspace'](arg1);
}

export function ListClosedReposByWorkspace(arg1, arg2, arg3) {
  return window['go']['controller']['repoController']['ListClosedReposByWorkspace'](arg1, arg2, arg3);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['repoController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['repoController']['OnStartup'](arg1);
}

export function OpenInFinder(arg1) {
  return window['go']['controller']['repoController']['OpenInFinder'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['controller']['repoController']['OpenInTerminal'](arg1);
}

export function OpenRepo(arg1) {
  return window['go']['controller']['repoController']['OpenRepo'](arg1);
}

export function RemoveRepo(arg1) {
  return window['go']['controller']['repoController']['RemoveRepo'](arg1);
}
