// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function BrowseDirectory():Promise<string>;

export function GetRepo(arg1:string):Promise<dto.RepoResponse>;

export function ListClosedReposByWorkspace(arg1:string,arg2:number,arg3:number):Promise<Array<dto.RepoResponse>>;

export function ListReposByWorkspace(arg1:string):Promise<Array<dto.RepoResponse>>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function OpenInFinder(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function OpenRepo(arg1:dto.CreateRepoRequest):Promise<dto.RepoResponse>;

export function RemoveRepo(arg1:string):Promise<void>;
