// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function ArchiveSession(arg1:string):Promise<void>;

export function CheckBranchExists(arg1:string,arg2:string):Promise<boolean>;

export function CreateSession(arg1:dto.CreateSessionRequest):Promise<dto.SessionResponse>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetSession(arg1:string):Promise<dto.SessionResponse>;

export function GetSessionOutput(arg1:string):Promise<string>;

export function GetUnpushedCommits(arg1:string):Promise<Array<string>>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitCommitFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function GitDiffFile(arg1:string,arg2:string):Promise<string>;

export function GitDiffFiles(arg1:string):Promise<Array<dto.DiffFileResponse>>;

export function GitGetFileContent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitPull(arg1:string,arg2:string):Promise<void>;

export function GitPush(arg1:string):Promise<void>;

export function GitSaveFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListBranches(arg1:string):Promise<Array<string>>;

export function ListSessions():Promise<Array<dto.SessionResponse>>;

export function ListSessionsByRepo(arg1:string):Promise<Array<dto.SessionResponse>>;

export function ListSessionsByTask(arg1:string):Promise<Array<dto.SessionResponse>>;

export function MoveSessionToTask(arg1:string,arg2:string):Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResumeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RunShortcut(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StartSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function UnarchiveSession(arg1:string):Promise<void>;
