// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveSession(arg1) {
  return window['go']['controller']['sessionController']['ArchiveSession'](arg1);
}

export function CheckBranchExists(arg1, arg2) {
  return window['go']['controller']['sessionController']['CheckBranchExists'](arg1, arg2);
}

export function CreateSession(arg1) {
  return window['go']['controller']['sessionController']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['controller']['sessionController']['DeleteSession'](arg1);
}

export function GetCurrentBranch(arg1) {
  return window['go']['controller']['sessionController']['GetCurrentBranch'](arg1);
}

export function GetSession(arg1) {
  return window['go']['controller']['sessionController']['GetSession'](arg1);
}

export function GetSessionOutput(arg1) {
  return window['go']['controller']['sessionController']['GetSessionOutput'](arg1);
}

export function GetUnpushedCommits(arg1) {
  return window['go']['controller']['sessionController']['GetUnpushedCommits'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['controller']['sessionController']['GitCommit'](arg1, arg2);
}

export function GitCommitFiles(arg1, arg2, arg3) {
  return window['go']['controller']['sessionController']['GitCommitFiles'](arg1, arg2, arg3);
}

export function GitDiffFile(arg1, arg2) {
  return window['go']['controller']['sessionController']['GitDiffFile'](arg1, arg2);
}

export function GitDiffFiles(arg1) {
  return window['go']['controller']['sessionController']['GitDiffFiles'](arg1);
}

export function GitGetFileContent(arg1, arg2, arg3) {
  return window['go']['controller']['sessionController']['GitGetFileContent'](arg1, arg2, arg3);
}

export function GitPull(arg1, arg2) {
  return window['go']['controller']['sessionController']['GitPull'](arg1, arg2);
}

export function GitPush(arg1) {
  return window['go']['controller']['sessionController']['GitPush'](arg1);
}

export function GitSaveFileContent(arg1, arg2, arg3) {
  return window['go']['controller']['sessionController']['GitSaveFileContent'](arg1, arg2, arg3);
}

export function ListBranches(arg1) {
  return window['go']['controller']['sessionController']['ListBranches'](arg1);
}

export function ListSessions() {
  return window['go']['controller']['sessionController']['ListSessions']();
}

export function ListSessionsByRepo(arg1) {
  return window['go']['controller']['sessionController']['ListSessionsByRepo'](arg1);
}

export function ListSessionsByTask(arg1) {
  return window['go']['controller']['sessionController']['ListSessionsByTask'](arg1);
}

export function MoveSessionToTask(arg1, arg2) {
  return window['go']['controller']['sessionController']['MoveSessionToTask'](arg1, arg2);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['sessionController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['sessionController']['OnStartup'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['controller']['sessionController']['RenameSession'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['controller']['sessionController']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResumeSession(arg1, arg2, arg3) {
  return window['go']['controller']['sessionController']['ResumeSession'](arg1, arg2, arg3);
}

export function RunShortcut(arg1, arg2) {
  return window['go']['controller']['sessionController']['RunShortcut'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['controller']['sessionController']['SendMessage'](arg1, arg2);
}

export function StartSession(arg1, arg2, arg3) {
  return window['go']['controller']['sessionController']['StartSession'](arg1, arg2, arg3);
}

export function StopSession(arg1) {
  return window['go']['controller']['sessionController']['StopSession'](arg1);
}

export function UnarchiveSession(arg1) {
  return window['go']['controller']['sessionController']['UnarchiveSession'](arg1);
}
