// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveTask(arg1) {
  return window['go']['controller']['taskController']['ArchiveTask'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['controller']['taskController']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['controller']['taskController']['DeleteTask'](arg1);
}

export function GetTask(arg1) {
  return window['go']['controller']['taskController']['GetTask'](arg1);
}

export function ListTasksByRepo(arg1) {
  return window['go']['controller']['taskController']['ListTasksByRepo'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['taskController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['taskController']['OnStartup'](arg1);
}

export function UnarchiveTask(arg1) {
  return window['go']['controller']['taskController']['UnarchiveTask'](arg1);
}
