// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function ArchiveTask(arg1:string):Promise<void>;

export function CreateTask(arg1:dto.CreateTaskRequest):Promise<dto.TaskResponse>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetTask(arg1:string):Promise<dto.TaskResponse>;

export function ListTasksByRepo(arg1:string):Promise<Array<dto.TaskResponse>>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RenameTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnarchiveTask(arg1:string):Promise<void>;
