// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {voiceruntime} from '../models';
import {context} from '../models';

export function InstallVoiceLanguage(arg1:string):Promise<voiceruntime.Status>;

export function InstallVoiceRuntime():Promise<voiceruntime.Status>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function UninstallVoiceRuntime():Promise<voiceruntime.Status>;

export function VoiceRuntimeStatus():Promise<voiceruntime.Status>;
