// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallVoiceRuntime() {
  return window['go']['controller']['voiceRuntimeController']['InstallVoiceRuntime']();
}

export function OnShutdown(arg1) {
  return window['go']['controller']['voiceRuntimeController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['voiceRuntimeController']['OnStartup'](arg1);
}

export function UninstallVoiceRuntime() {
  return window['go']['controller']['voiceRuntimeController']['UninstallVoiceRuntime']();
}

export function VoiceRuntimeStatus() {
  return window['go']['controller']['voiceRuntimeController']['VoiceRuntimeStatus']();
}
