// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnShutdown(arg1) {
  return window['go']['controller']['windowController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['windowController']['OnStartup'](arg1);
}

export function OpenWorkspaceWindow(arg1) {
  return window['go']['controller']['windowController']['OpenWorkspaceWindow'](arg1);
}
