// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseClaudeConfigDir() {
  return window['go']['controller']['workspaceController']['BrowseClaudeConfigDir']();
}

export function BrowseMcpConfigFile() {
  return window['go']['controller']['workspaceController']['BrowseMcpConfigFile']();
}

export function CreateWorkspace(arg1) {
  return window['go']['controller']['workspaceController']['CreateWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['controller']['workspaceController']['DeleteWorkspace'](arg1);
}

export function GetWorkspace(arg1) {
  return window['go']['controller']['workspaceController']['GetWorkspace'](arg1);
}

export function ListWorkspaces() {
  return window['go']['controller']['workspaceController']['ListWorkspaces']();
}

export function OnShutdown(arg1) {
  return window['go']['controller']['workspaceController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['workspaceController']['OnStartup'](arg1);
}

export function UpdateWorkspace(arg1) {
  return window['go']['controller']['workspaceController']['UpdateWorkspace'](arg1);
}

export function ValidatePaths(arg1, arg2) {
  return window['go']['controller']['workspaceController']['ValidatePaths'](arg1, arg2);
}
